name: Deploy UI to gh-pages

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./flow-ui

      - name: Build project
        run: npm run build
        working-directory: ./flow-ui

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./flow-ui/dist
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
