name: Python package

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies
        run: poetry install

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: >-
            --color=always
            --from-ref ${{ github.event.pull_request.base.sha != '' && github.event.pull_request.base.sha || 'origin/main' }}
            --to-ref ${{ github.event.pull_request.head.sha != '' && github.event.pull_request.head.sha || 'HEAD' }}

      - name: Test with pytest
        run: |
          poetry run pytest
